// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtppMAi_tAgH9T84oXGwPPbSPj5wHxoGY',
    appId: '1:279491510509:web:c3c54ea29152d39fb40ce4',
    messagingSenderId: '279491510509',
    projectId: 'e-com-98eba',
    authDomain: 'e-com-98eba.firebaseapp.com',
    storageBucket: 'e-com-98eba.appspot.com',
    measurementId: 'G-RTFH89BBG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46X2trsCOvwODRXajOgdKGw6UMMwiJVg',
    appId: '1:279491510509:android:1bbf5d18f9bfeaa8b40ce4',
    messagingSenderId: '279491510509',
    projectId: 'e-com-98eba',
    storageBucket: 'e-com-98eba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUiWtBX2rlKDXbnZHAUssr22xVFGI4Iw',
    appId: '1:279491510509:ios:0ffae70818934433b40ce4',
    messagingSenderId: '279491510509',
    projectId: 'e-com-98eba',
    storageBucket: 'e-com-98eba.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUiWtBX2rlKDXbnZHAUssr22xVFGI4Iw',
    appId: '1:279491510509:ios:a99d633980ed3268b40ce4',
    messagingSenderId: '279491510509',
    projectId: 'e-com-98eba',
    storageBucket: 'e-com-98eba.appspot.com',
    iosBundleId: 'com.example.eCom.RunnerTests',
  );
}
